export interface ZenSpark {
  id: string;
  title: string;
  summary: string;
  readingTimeMinutes: number;
  category: 'Geopolitics' | 'Climate Diplomacy' | 'Civic Tech' | 'Bioethics' | 'Youth Governance' | 'Economics' | 'AI Ethics' | 'International Law';
  authorName: string;
  authorUsername: string;
  authorAvatar?: string;
  keyTakeaways: string[];
  fullDossier: string;
  treatyClauseReference?: string;
  tags: string[];
  likes: number;
  likedBy: string[];
  saves: number;
  savedBy: string[];
  createdAt: string;
}

export const INITIAL_SPARKS: ZenSpark[] = [
  {
    id: 'spark_ai_sovereign_2026',
    title: 'The 2026 Sovereign AI Compact: Decentralized Inference and Multilateral Oversight',
    summary: 'An executive 5-minute briefing on the framework establishing open-weights infrastructure as public diplomatic utilities while safeguarding national compute security.',
    readingTimeMinutes: 5,
    category: 'AI Ethics',
    authorName: 'Zenvitra Secretariat',
    authorUsername: 'secretariat',
    authorAvatar: undefined,
    keyTakeaways: [
      'Multi-stakeholder compute audits must replace closed proprietary self-reporting by Q3 2026.',
      'Developing nations secure 15% guaranteed access to cross-border federated inference clusters.',
      'Treaty-level verification nodes allow non-intrusive watermarking without compromising user encryption.'
    ],
    fullDossier: `The democratization of foundational intelligence represents the primary geopolitical frontier of this decade. When AI weights and compute power concentrate within a handful of multinational entities, smaller nation-states and civil society lose digital sovereignty.

1. THE PUBLIC COMPUTE COMMONS
Historically, international telecommunication corridors and maritime trade routes received multilateral treaty protection under the Geneva and Vienna conventions. We propose that Tier-1 frontier compute clusters hosting non-commercial civic models be accorded 'Neutral Infrastructure Status' under UN charter Chapter VII.

2. VERIFICATION WITHOUT SURVEILLANCE
A crucial deadlock in current diplomatic negotiations is the verification paradox: how do signatory states confirm that training runs comply with safety limits without exposing proprietary source code? The solution lies in Zero-Knowledge Compute Proofs (ZKCP). Verifier nodes attest that compute cycles remained within bounded thermal and algorithmic tolerances without ever reading training weights.

3. YOUTH & GLOBAL SOUTH ENFRANCHISEMENT
Under Resolution 41-B, a 15% quota of all federated inference capacity generated by treaty members is pooled into the Sovereign Youth Commons. High schools, municipal labs, and youth delegates can execute policy modeling, disaster simulation, and legislative analysis without commercial API tollgates.`,
    treatyClauseReference: 'UN-GA-81/RES-41B §4',
    tags: ['AI-Safety', 'Sovereignty', 'ComputeCommons', 'ZK-Proofs'],
    likes: 342,
    likedBy: [],
    saves: 189,
    savedBy: [],
    createdAt: '2 hours ago'
  },
  {
    id: 'spark_climate_loss_damage_2026',
    title: 'Rewiring the Loss and Damage Fund: Direct Micro-Grants for Island Nations',
    summary: 'Why traditional multilateral development banks fail climate-vulnerable communities and how algorithmic smart-escrow delivers disaster relief within 90 minutes.',
    readingTimeMinutes: 5,
    category: 'Climate Diplomacy',
    authorName: 'Pacific Islands Climate Dais',
    authorUsername: 'pacific_dais',
    authorAvatar: undefined,
    keyTakeaways: [
      'Parametric satellite triggers unlock capital in <90 mins post-disaster, avoiding bureaucrat stall.',
      'Direct decentralized liquidity corridors bypass 30% intermediary administrative overhead.',
      'Sovereign indigenous councils maintain veto authority over relocation infrastructure placement.'
    ],
    fullDossier: `During the COP30 negotiations in Belém, the Pacific Islands Forum presented undisputed evidence: conventional aid frameworks require an average of 412 days between a Category 5 typhoon landfall and the disbursement of reconstruction capital. By then, topsoil salinity is irreversible and displaced populations face catastrophic food insecurity.

1. PARAMETRIC ESCROW DISPATCH
By integrating Copernicus and Sentinel-3 synthetic aperture radar telemetry with decentralized smart escrows, capital is released automatically when storm surge thresholds surpass 2.4 meters. No manual claim forms, no bilateral committee approvals.

2. 100% AUDITABLE SOVEREIGN LEDGER
Traditional bilateral relief loses up to 28% of fund value in currency exchange fees, third-party logistics overheads, and administrative bottlenecks. By executing disbursements in tokenized treasury reserves directly to accredited island municipalities, loss margins drop below 0.2%.

3. INDIGENOUS ADAPTATION RESERVES
Relocation cannot be dictated by foreign engineering firms. Under Clause 12 of the Suva Declaration, indigenous councils hold 51% board control over all seawall, mangrove replenishment, and desalinization infrastructure tenders.`,
    treatyClauseReference: 'UNFCCC-COP30/PA-Art8 §12',
    tags: ['ClimateRelief', 'LossAndDamage', 'SmartEscrow', 'Copernicus'],
    likes: 518,
    likedBy: [],
    saves: 274,
    savedBy: [],
    createdAt: '5 hours ago'
  },
  {
    id: 'spark_youth_un_governance',
    title: 'Youth Plenary Architecture: Embedding Voting Quorums into UN Resolutions',
    summary: 'A 5-minute deep dive on institutionalizing permanent youth delegation seats with binding amendment veto rights across multilateral treaties.',
    readingTimeMinutes: 5,
    category: 'Youth Governance',
    authorName: 'UNGA Youth Dais Plenary',
    authorUsername: 'unga_plenary',
    authorAvatar: undefined,
    keyTakeaways: [
      'Youth delegates under 28 receive mandatory consultative voting status in 4 UN Main Committees.',
      'Every draft resolution impacting intergenerational equity requires an Intergenerational Impact Score (IIS).',
      'The Sovereign Youth Passport platform acts as the verified accreditation pipeline for global youth delegates.'
    ],
    fullDossier: `For over seven decades, young citizens—who constitute over 50% of the global population—have been relegated to ceremonial side-events, Youth Advisory Groups with zero statutory power, and photo-op declarations. The 2026 Pact for the Future introduces the most significant procedural shift in UN history.

1. MANDATORY PLENARY QUORUM
Starting with the 81st Session of the UN General Assembly, all resolutions under the Second (Economic & Financial) and Third (Social, Humanitarian & Cultural) Committees must incorporate a minimum of 24 accredited youth co-sponsors representing all 5 UN regional groups.

2. THE INTERGENERATIONAL IMPACT SCORE (IIS)
Every legislative text submitted for floor debate must include a validated IIS index measuring resource depletion, sovereign debt burden, and climate degradation over a 50-year horizon. If an IIS score drops below 60/100, a 30-day deliberation window is triggered for youth envoy redline amendments.

3. DIRECT DEMOCRATIC CITATION
Delegates submit amendments directly through the verified ZenVitra pulse matrix. Redlines receiving over 10,000 verified youth delegate endorsements are automatically appended to the official conference room paper (CRP) as formal non-paper submissions.`,
    treatyClauseReference: 'UN-PFF-2026/CH3 §18',
    tags: ['YouthPlenary', 'UNReform', 'IntergenerationalJustice', 'Diplomacy'],
    likes: 890,
    likedBy: [],
    saves: 432,
    savedBy: [],
    createdAt: '1 day ago'
  },
  {
    id: 'spark_digital_carbon_rail',
    title: 'Digital Carbon Passports: Eliminating Greenwashing in Maritime Supply Chains',
    summary: 'How cryptographic fuel tracing and port-of-entry IoT sensors are holding shipping conglomerates accountable to the 2030 Net-Zero IMO Accord.',
    readingTimeMinutes: 5,
    category: 'Civic Tech',
    authorName: 'Civic Technology Working Group',
    authorUsername: 'civic_tech',
    authorAvatar: undefined,
    keyTakeaways: [
      'Fuel bunker mass-flow meters cryptographically sign fuel quality data directly to maritime ledgers.',
      'Vessels failing sulfur and carbon caps face automatic port fee surcharges at 42 international maritime hubs.',
      'Public open-access dashboards enable citizen scientists to track real-time container emissions.'
    ],
    fullDossier: `Maritime shipping accounts for approximately 3% of global greenhouse emissions—surpassing the annual emissions of many G20 nations. For years, 'paper carbon offsets' provided maritime carriers with plausible deniability while high-sulfur heavy fuel oil was burned in international waters.

1. CRYPTOGRAPHIC FUEL TRACEABILITY
By deploying sealed Mass Flow Meters (MFM) and exhaust gas continuous emission monitoring systems (CEMS) linked to tamper-evident hardware security modules, fuel consumption is recorded every 60 seconds with GPS and bathymetric data.

2. AUTOMATED HARBOR CLEARANCE TARIFFS
Under the Singapore-Rotterdam Green Corridor Treaty, vessels entering territorial waters submit their verifiable emission credential to harbor authorities. Clean ammonia and methanol-powered vessels receive automated 40% berthing discounts, while violators incur non-negotiable carbon penalty tariffs.

3. CIVIC DATA TRANSPARENCY
All raw sensor telemetry is streamed to open public indices. Civic tech organizations and academic researchers can independently verify fleet emissions without relying on self-reported carrier ESG brochures.`,
    treatyClauseReference: 'IMO-MARPOL-AnnexVI/Rev26',
    tags: ['MaritimeTech', 'CarbonTracking', 'SupplyChain', 'GreenCorridor'],
    likes: 275,
    likedBy: [],
    saves: 140,
    savedBy: [],
    createdAt: '1 day ago'
  },
  {
    id: 'spark_brics_settlement_currency',
    title: 'The Multi-Currency Sovereign Clearing Grid: Resilience Beyond Single-Reserve Hegemony',
    summary: 'Examining the architecture of zero-custody multilateral currency baskets for emerging market agricultural and energy trade.',
    readingTimeMinutes: 5,
    category: 'Economics',
    authorName: 'Global South Economic Forum',
    authorUsername: 'gsef_multilateral',
    authorAvatar: undefined,
    keyTakeaways: [
      'Local currency clearing reduces foreign exchange friction by $48B annually across Global South trade.',
      'Central bank digital reserves settle cross-border agricultural shipments within 12 seconds.',
      'Zero-custody liquidity hubs ensure that food and fertilizer shipments remain immune to unilateral embargoes.'
    ],
    fullDossier: `When central bank foreign exchange reserves were frozen in 2022, central banks across Asia, Latin America, and Africa accelerated development of independent clearing corridors. The resulting Multi-Currency Sovereign Clearing Grid (MCSCG) represents the biggest shift in international trade finance since the 1944 Bretton Woods agreement.

1. ATOMIC LOCAL-CURRENCY SWAPS
Under traditional trade finance, a coffee shipment from Brazil to Kenya requires an intermediary conversion from Brazilian Real to USD, and then USD to Kenyan Shillings, incurring multiple correspondent banking fees. MCSCG enables instantaneous atomic swaps between central bank liquidity pools, settling trade in seconds.

2. HUMANITARIAN & COMMODITY IMMUNITY
Article 4 of the Bandung Economic Framework guarantees that transactions involving wheat, fertilizer, medical equipment, and renewable energy components cannot be frozen or blacklisted by third-party financial institutions.

3. DECENTRALIZED CLEARING HUBS
Rather than routing through a single geographic clearing house, the network operates across 12 distributed sovereign validator nodes hosted by participating central banks and multilateral regional development banks.`,
    treatyClauseReference: 'BEF-Art4/MCSCG-2026',
    tags: ['Macroeconomics', 'TradeFinance', 'BandungFramework', 'EmergingMarkets'],
    likes: 620,
    likedBy: [],
    saves: 310,
    savedBy: [],
    createdAt: '2 days ago'
  }
];
