/**
 * OFFICIAL SOURCES & CITATION DIRECTORY
 * Extracted and structured from SASSY Constituent Assembly 2026 Reference Material
 * Prepared by Hit Upadhyay (Chairman), Kavyanshi (Deputy Chairman), Yuveer Chhatwani (Advisor)
 */

export interface SourceItem {
  id: string;
  name: string;
  url: string;
  category: 'government' | 'academic' | 'national_newspaper' | 'parliamentary_broadcast' | 'investigative_media' | 'international';
  description: string;
  badge: string;
  badgeColor: string;
}

export const OFFICIAL_SOURCES_DIRECTORY: SourceItem[] = [
  // ── 1. PRIMARY GOVERNMENT PORTALS & LEGAL REGISTRIES ──
  {
    id: 'cad-india',
    name: 'Constituent Assembly Debates (CAD India)',
    url: 'https://cadindia.clpr.org.in/',
    category: 'government',
    description: 'Verbatim historical debates (1946–1950) and original intent behind every article.',
    badge: 'Constituent Assembly',
    badgeColor: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
  },
  {
    id: 'legislative-dept',
    name: 'Legislative Department (Ministry of Law & Justice)',
    url: 'https://legislative.gov.in',
    category: 'government',
    description: 'Official authoritative text of the Constitution of India, Central Acts, and Gazette notifications.',
    badge: 'Ministry of Law',
    badgeColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'sci-gov',
    name: 'Supreme Court of India',
    url: 'https://sci.gov.in',
    category: 'government',
    description: 'Official judgments, orders, case status, constitution bench rulings, and judicial precedents.',
    badge: 'Apex Judiciary',
    badgeColor: 'bg-purple-500/10 text-purple-300 border-purple-500/30',
  },
  {
    id: 'lok-sabha',
    name: 'Lok Sabha (House of the People)',
    url: 'https://loksabha.nic.in',
    category: 'government',
    description: 'Bills, legislative business, questions, debates, and standing committee reports.',
    badge: 'Parliament',
    badgeColor: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'rajya-sabha',
    name: 'Rajya Sabha (Council of States)',
    url: 'https://rajyasabha.nic.in',
    category: 'government',
    description: 'Upper House debates, bills passed, committee dossiers, and parliamentary archives.',
    badge: 'Parliament',
    badgeColor: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'pib-india',
    name: 'Press Information Bureau (PIB)',
    url: 'https://pib.gov.in',
    category: 'government',
    description: 'Official press communiques, ministry press releases, and Government of India fact checks.',
    badge: 'Official Press',
    badgeColor: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
  },
  {
    id: 'eci-india',
    name: 'Election Commission of India (ECI)',
    url: 'https://eci.gov.in',
    category: 'government',
    description: 'Electoral data, election conduct rules, political party notifications, and Model Code of Conduct.',
    badge: 'Constitutional Body',
    badgeColor: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
  },
  {
    id: 'cag-india',
    name: 'Comptroller & Auditor General of India (CAG)',
    url: 'https://cag.gov.in',
    category: 'government',
    description: 'Audit reports on Union, State finances, public undertakings, and constitutional compliance.',
    badge: 'CAG Audit',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },
  {
    id: 'law-commission',
    name: 'Law Commission of India',
    url: 'https://lawcommissionofindia.nic.in',
    category: 'government',
    description: 'Comprehensive research recommendations and reports on legislative and constitutional reforms.',
    badge: 'Law Reform',
    badgeColor: 'bg-indigo-500/10 text-indigo-300 border-indigo-500/30',
  },
  {
    id: 'census-india',
    name: 'Census of India',
    url: 'https://censusindia.gov.in',
    category: 'government',
    description: 'Official demographic, economic, and sociolinguistic statistics of the Republic of India.',
    badge: 'Demographics',
    badgeColor: 'bg-teal-500/10 text-teal-300 border-teal-500/30',
  },
  {
    id: 'niti-aayog',
    name: 'NITI Aayog (National Institution for Transforming India)',
    url: 'https://niti.gov.in',
    category: 'government',
    description: 'Strategic policy blueprints, development indices, and public policy monitoring frameworks.',
    badge: 'Think Tank',
    badgeColor: 'bg-violet-500/10 text-violet-300 border-violet-500/30',
  },

  // ── 2. LEGAL RESEARCH & ACADEMIC INSTITUTIONS ──
  {
    id: 'clpr',
    name: 'Centre for Law and Policy Research (CLPR)',
    url: 'https://clpr.org.in',
    category: 'academic',
    description: 'Constitutional law research, historical assembly debates analysis, and legal scholarship.',
    badge: 'Legal Research',
    badgeColor: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'vidhi-legal',
    name: 'Vidhi Centre for Legal Policy',
    url: 'https://vidhilegalpolicy.in',
    category: 'academic',
    description: 'Independent legal think tank advising on legislative drafting, constitutional law, and judicial reforms.',
    badge: 'Legal Policy',
    badgeColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'ili-delhi',
    name: 'Indian Law Institute (ILI)',
    url: 'https://ili.ac.in',
    category: 'academic',
    description: 'Premier legal research institution established under the aegis of the Supreme Court of India.',
    badge: 'Academic',
    badgeColor: 'bg-purple-500/10 text-purple-300 border-purple-500/30',
  },
  {
    id: 'prs-india',
    name: 'PRS Legislative Research',
    url: 'https://prsindia.org',
    category: 'academic',
    description: 'Non-partisan research analyzing parliamentary bills, MP performance, and legislative metrics.',
    badge: 'Parliamentary Research',
    badgeColor: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
  },

  // ── 3. NATIONAL NEWSPAPERS (Primary Press) ──
  {
    id: 'the-hindu',
    name: 'The Hindu',
    url: 'https://www.thehindu.com',
    category: 'national_newspaper',
    description: 'National newspaper of record known for rigorous constitutional, judicial, and legislative reporting.',
    badge: 'National Daily',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },
  {
    id: 'indian-express',
    name: 'The Indian Express',
    url: 'https://indianexpress.com',
    category: 'national_newspaper',
    description: 'Foremost investigative daily renowned for in-depth coverage of politics, governance, and public policy.',
    badge: 'National Daily',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },
  {
    id: 'economic-times',
    name: 'The Economic Times',
    url: 'https://economictimes.indiatimes.com',
    category: 'national_newspaper',
    description: "India's leading business and economic daily covering fiscal policy, trade, and economic legislation.",
    badge: 'Financial Press',
    badgeColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'hindustan-times',
    name: 'Hindustan Times',
    url: 'https://www.hindustantimes.com',
    category: 'national_newspaper',
    description: 'Major national daily covering national politics, international affairs, and public administration.',
    badge: 'National Daily',
    badgeColor: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
  },
  {
    id: 'times-of-india',
    name: 'The Times of India',
    url: 'https://timesofindia.indiatimes.com',
    category: 'national_newspaper',
    description: 'Wide-circulation daily covering legal affairs, parliamentary proceedings, and civic events.',
    badge: 'National Daily',
    badgeColor: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
  },

  // ── 4. PARLIAMENTARY BROADCASTS & VIDEO ARCHIVES ──
  {
    id: 'sansad-tv',
    name: 'Sansad TV',
    url: 'https://sansadtv.nic.in',
    category: 'parliamentary_broadcast',
    description: 'Official broadcaster of Indian Parliament: live proceedings, legislative debates, and constitutional shows.',
    badge: 'Official Broadcast',
    badgeColor: 'bg-amber-500/15 text-amber-300 border-amber-500/40',
  },
  {
    id: 'loksabha-tv-archives',
    name: 'Lok Sabha TV Archives',
    url: 'https://loksabha.nic.in',
    category: 'parliamentary_broadcast',
    description: 'Historical video and transcript records of Lok Sabha floor speeches, motions, and zero hour debates.',
    badge: 'Broadcast Archive',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
  },

  // ── 5. SUPPLEMENTARY & INVESTIGATIVE MEDIA (For debate corroboration) ──
  {
    id: 'the-print',
    name: 'The Print',
    url: 'https://theprint.in',
    category: 'investigative_media',
    description: 'Digital news platform specializing in governance, strategic affairs, politics, and legal analysis.',
    badge: 'Digital Journal',
    badgeColor: 'bg-purple-500/10 text-purple-300 border-purple-500/30',
  },
  {
    id: 'live-mint',
    name: 'Mint',
    url: 'https://www.livemint.com',
    category: 'investigative_media',
    description: 'Wall Street Journal affiliate focusing on policy metrics, macro-economics, and legal regulatory trends.',
    badge: 'Financial & Policy',
    badgeColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'the-wire',
    name: 'The Wire',
    url: 'https://thewire.in',
    category: 'investigative_media',
    description: 'Independent non-profit journalism focused on civil liberties, constitutional rights, and public scrutiny.',
    badge: 'Investigative',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },
  {
    id: 'newslaundry',
    name: 'Newslaundry',
    url: 'https://www.newslaundry.com',
    category: 'investigative_media',
    description: 'Subscriber-supported media critique, field reporting, and public accountability investigations.',
    badge: 'Media Critique',
    badgeColor: 'bg-orange-500/10 text-orange-300 border-orange-500/30',
  },
  {
    id: 'molitics',
    name: 'Molitics',
    url: 'https://molitics.in',
    category: 'investigative_media',
    description: 'Civic-political journalism, electoral analysis, constituency tracking, and youth policy debates.',
    badge: 'Political Tracker',
    badgeColor: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'frontline',
    name: 'Frontline Magazine',
    url: 'https://frontline.thehindu.com',
    category: 'investigative_media',
    description: 'Fortnightly national magazine covering deep constitutional history, foreign policy, and socio-economic affairs.',
    badge: 'In-Depth Journal',
    badgeColor: 'bg-red-500/10 text-red-300 border-red-500/30',
  },
  {
    id: 'outlook-india',
    name: 'Outlook India',
    url: 'https://www.outlookindia.com',
    category: 'investigative_media',
    description: 'Comprehensive public interest weekly analyzing politics, culture, and constitutional jurisprudence.',
    badge: 'Public Interest',
    badgeColor: 'bg-pink-500/10 text-pink-300 border-pink-500/30',
  },
  {
    id: 'india-today',
    name: 'India Today',
    url: 'https://www.indiatoday.in',
    category: 'investigative_media',
    description: 'Long-standing national news magazine covering national politics, opinion polls, and governance summits.',
    badge: 'National Media',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },
  {
    id: 'time-magazine',
    name: 'TIME Magazine',
    url: 'https://time.com',
    category: 'investigative_media',
    description: 'Global editorial reporting on international politics, governance summits, and transformative youth leaders.',
    badge: 'International Press',
    badgeColor: 'bg-rose-500/10 text-rose-300 border-rose-500/30',
  },

  // ── 6. INTERNATIONAL CONSTITUTIONAL PLATFORMS ──
  {
    id: 'un-digital-library',
    name: 'United Nations Digital Library',
    url: 'https://digitallibrary.un.org',
    category: 'international',
    description: 'UN official documents, voting records, resolutions, and speech transcripts.',
    badge: 'United Nations',
    badgeColor: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
  },
  {
    id: 'ipu-parliament',
    name: 'Inter-Parliamentary Union (IPU)',
    url: 'https://www.ipu.org',
    category: 'international',
    description: 'Global organization of national parliaments; comparative parliamentary law and human rights data.',
    badge: 'Global Parliament',
    badgeColor: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'constitution-project',
    name: 'Constitute Project',
    url: 'https://www.constituteproject.org',
    category: 'international',
    description: 'Comparative database containing constitutions of the world indexed by topic and clause.',
    badge: 'Comparative Law',
    badgeColor: 'bg-teal-500/10 text-teal-300 border-teal-500/30',
  },
];
