export interface EmojiItem {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const UNIVERSAL_EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['happy', 'smile', 'joy'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'joy', 'smile'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'joy', 'laugh'] },
      { char: '😁', name: 'beaming face', keywords: ['smile', 'happy', 'grin'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'haha'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['relief', 'whew'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'lol'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'lol'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile', 'calm'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
      { char: '🫠', name: 'melting face', keywords: ['melt', 'hot'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'warm'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'crush'] },
      { char: '😍', name: 'heart-eyes', keywords: ['love', 'adore'] },
      { char: '🤩', name: 'star-struck', keywords: ['stars', 'amazed', 'wow'] },
      { char: '😘', name: 'blowing kiss', keywords: ['kiss', 'love'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss'] },
      { char: '😚', name: 'kissing face closed eyes', keywords: ['kiss'] },
      { char: '🥲', name: 'smiling face with tear', keywords: ['grateful', 'moved'] },
      { char: '😋', name: 'savoring food', keywords: ['yum', 'delicious'] },
      { char: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
      { char: '😜', name: 'winking with tongue', keywords: ['wink', 'crazy'] },
      { char: '🤪', name: 'zany face', keywords: ['wild', 'goofy'] },
      { char: '😝', name: 'squinting with tongue', keywords: ['playful'] },
      { char: '🤑', name: 'money-mouth', keywords: ['money', 'rich', 'dollar'] },
      { char: '🤗', name: 'smiling with open hands', keywords: ['hug', 'welcome'] },
      { char: '🫣', name: 'peeking eye', keywords: ['peek', 'shy'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'ponder'] },
      { char: '🫡', name: 'saluting face', keywords: ['salute', 'respect'] },
      { char: '🤐', name: 'zipper-mouth', keywords: ['silent', 'secret'] },
      { char: '🤨', name: 'raised eyebrow', keywords: ['skeptical'] },
      { char: '😐', name: 'neutral face', keywords: ['meh', 'blank'] },
      { char: '😑', name: 'expressionless', keywords: ['unimpressed'] },
      { char: '😶', name: 'without mouth', keywords: ['silent'] },
      { char: '🫥', name: 'dotted line face', keywords: ['invisible'] },
      { char: '😏', name: 'smirking face', keywords: ['smirk', 'cool'] },
      { char: '😒', name: 'unamused face', keywords: ['annoyed'] },
      { char: '🙄', name: 'rolling eyes', keywords: ['whatever'] },
      { char: '😬', name: 'grimacing face', keywords: ['awkward'] },
      { char: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief'] },
      { char: '🤥', name: 'lying face', keywords: ['pinocchio', 'lie'] },
      { char: '🫨', name: 'shaking face', keywords: ['shock'] },
      { char: '😌', name: 'relieved face', keywords: ['peaceful', 'zen'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'down'] },
      { char: '😪', name: 'sleepy face', keywords: ['tired'] },
      { char: '🤤', name: 'drooling face', keywords: ['craving'] },
      { char: '😴', name: 'sleeping face', keywords: ['zzz', 'asleep'] },
      { char: '😷', name: 'medical mask', keywords: ['sick', 'mask'] },
      { char: '🤒', name: 'thermometer', keywords: ['fever', 'ill'] },
      { char: '🤕', name: 'head-bandage', keywords: ['hurt', 'injury'] },
      { char: '🤢', name: 'nauseated', keywords: ['gross', 'sick'] },
      { char: '🤮', name: 'vomiting', keywords: ['puke', 'barf'] },
      { char: '🤧', name: 'sneezing', keywords: ['sneeze', 'cold'] },
      { char: '🥵', name: 'hot face', keywords: ['heat', 'sweat'] },
      { char: '🥶', name: 'cold face', keywords: ['freezing', 'ice'] },
      { char: '🥴', name: 'woozy face', keywords: ['dizzy', 'tipsy'] },
      { char: '😵', name: 'crossed-out eyes', keywords: ['passed out'] },
      { char: '😵‍💫', name: 'spiral eyes', keywords: ['hypnotized'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind blown', 'boom'] },
      { char: '🤠', name: 'cowboy hat', keywords: ['western', 'yeehaw'] },
      { char: '🥳', name: 'partying face', keywords: ['celebrate', 'party'] },
      { char: '🥸', name: 'disguised face', keywords: ['spy', 'glasses'] },
      { char: '😎', name: 'sunglasses', keywords: ['cool', 'rad'] },
      { char: '🤓', name: 'nerd face', keywords: ['geek', 'smart'] },
      { char: '🧐', name: 'monocle', keywords: ['classy'] },
      { char: '😕', name: 'confused face', keywords: ['unsure'] },
      { char: '😟', name: 'worried face', keywords: ['anxious'] },
      { char: '🙁', name: 'slightly frowning', keywords: ['sad'] },
      { char: '☹️', name: 'frowning face', keywords: ['sad'] },
      { char: '😮', name: 'open mouth', keywords: ['surprise'] },
      { char: '😯', name: 'hushed face', keywords: ['shock'] },
      { char: '😲', name: 'astonished face', keywords: ['stunned'] },
      { char: '😳', name: 'flushed face', keywords: ['blush', 'shy'] },
      { char: '🥺', name: 'pleading face', keywords: ['puppy eyes', 'please'] },
      { char: '🥹', name: 'holding back tears', keywords: ['emotional'] },
      { char: '😦', name: 'frowning open mouth', keywords: ['alarmed'] },
      { char: '😧', name: 'anguished face', keywords: ['distressed'] },
      { char: '😨', name: 'fearful face', keywords: ['scared'] },
      { char: '😰', name: 'anxious with sweat', keywords: ['panic'] },
      { char: '😥', name: 'relieved face', keywords: ['phew'] },
      { char: '😢', name: 'crying face', keywords: ['tear', 'sad'] },
      { char: '😭', name: 'loudly crying', keywords: ['sobbing', 'bawling'] },
      { char: '😱', name: 'screaming in fear', keywords: ['scream', 'shock'] },
      { char: '😖', name: 'confounded face', keywords: ['upset'] },
      { char: '😣', name: 'persevering face', keywords: ['struggling'] },
      { char: '😞', name: 'disappointed face', keywords: ['down'] },
      { char: '😓', name: 'downcast with sweat', keywords: ['stress'] },
      { char: '😩', name: 'weary face', keywords: ['tired'] },
      { char: '😫', name: 'tired face', keywords: ['exhausted'] },
      { char: '🥱', name: 'yawning face', keywords: ['sleepy'] },
      { char: '😤', name: 'steam from nose', keywords: ['triumph', 'fuming'] },
      { char: '😡', name: 'enraged face', keywords: ['furious', 'rage'] },
      { char: '😠', name: 'angry face', keywords: ['mad'] },
      { char: '🤬', name: 'symbols on mouth', keywords: ['cursing', 'swearing'] },
      { char: '😈', name: 'smiling with horns', keywords: ['devil', 'mischief'] },
      { char: '👿', name: 'angry with horns', keywords: ['demon'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'skeleton'] },
      { char: '☠️', name: 'skull and crossbones', keywords: ['danger', 'pirate'] },
      { char: '💩', name: 'pile of poo', keywords: ['poop'] },
      { char: '🤡', name: 'clown', keywords: ['circus', 'joker'] },
      { char: '👹', name: 'ogre', keywords: ['monster'] },
      { char: '👺', name: 'goblin', keywords: ['tengu'] },
      { char: '👻', name: 'ghost', keywords: ['spooky', 'boo'] },
      { char: '👽', name: 'alien', keywords: ['extraterrestrial', 'ufo'] },
      { char: '👾', name: 'alien monster', keywords: ['space invaders'] },
      { char: '🤖', name: 'robot', keywords: ['bot', 'ai'] },
      { char: '😺', name: 'grinning cat', keywords: ['kitten'] },
      { char: '😸', name: 'smiling cat', keywords: ['cat'] },
      { char: '😹', name: 'joy cat', keywords: ['cat lol'] },
      { char: '😻', name: 'heart-eyes cat', keywords: ['cat love'] },
      { char: '😼', name: 'smirking cat', keywords: ['cat smirk'] },
      { char: '😽', name: 'kissing cat', keywords: ['cat kiss'] },
      { char: '🙀', name: 'weary cat', keywords: ['cat scream'] },
      { char: '😿', name: 'crying cat', keywords: ['cat sad'] },
      { char: '😾', name: 'pouting cat', keywords: ['cat angry'] },
      { char: '🙈', name: 'see-no-evil', keywords: ['monkey', 'shy'] },
      { char: '🙉', name: 'hear-no-evil', keywords: ['monkey'] },
      { char: '🙊', name: 'speak-no-evil', keywords: ['monkey'] },
      { char: '💋', name: 'kiss mark', keywords: ['lips'] },
      { char: '💌', name: 'love letter', keywords: ['romance'] },
      { char: '💘', name: 'heart with arrow', keywords: ['cupid'] },
      { char: '💝', name: 'heart with ribbon', keywords: ['gift'] },
      { char: '💖', name: 'sparkling heart', keywords: ['love'] },
      { char: '💗', name: 'growing heart', keywords: ['pulse'] },
      { char: '💓', name: 'beating heart', keywords: ['heartbeat'] },
      { char: '💞', name: 'revolving hearts', keywords: ['romance'] },
      { char: '💕', name: 'two hearts', keywords: ['love'] },
      { char: '💔', name: 'broken heart', keywords: ['sad', 'breakup'] },
      { char: '❤️‍🔥', name: 'heart on fire', keywords: ['passion'] },
      { char: '❤️', name: 'red heart', keywords: ['love'] },
      { char: '🩷', name: 'pink heart', keywords: ['sweet'] },
      { char: '🧡', name: 'orange heart', keywords: ['friendship'] },
      { char: '💛', name: 'yellow heart', keywords: ['loyalty'] },
      { char: '💚', name: 'green heart', keywords: ['nature'] },
      { char: '💙', name: 'blue heart', keywords: ['trust'] },
      { char: '🩵', name: 'light blue heart', keywords: ['peace'] },
      { char: '💜', name: 'purple heart', keywords: ['royalty'] },
      { char: '🖤', name: 'black heart', keywords: ['dark'] },
      { char: '🩶', name: 'grey heart', keywords: ['silver'] },
      { char: '🤍', name: 'white heart', keywords: ['pure'] },
      { char: '🤎', name: 'brown heart', keywords: ['earth'] },
      { char: '💯', name: 'hundred points', keywords: ['perfect', '100'] },
      { char: '💥', name: 'collision', keywords: ['boom', 'blast'] },
      { char: '💫', name: 'dizzy star', keywords: ['sparkle'] },
      { char: '💬', name: 'speech balloon', keywords: ['chat', 'talk'] },
      { char: '💭', name: 'thought balloon', keywords: ['think', 'dream'] }
    ]
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: '👋',
    emojis: [
      { char: '👋', name: 'waving hand', keywords: ['hello', 'bye'] },
      { char: '🤚', name: 'raised back of hand', keywords: ['stop'] },
      { char: '✋', name: 'raised hand', keywords: ['stop', 'high five'] },
      { char: '🖖', name: 'vulcan salute', keywords: ['spock'] },
      { char: '🫱', name: 'right hand', keywords: ['reach'] },
      { char: '🫲', name: 'left hand', keywords: ['reach'] },
      { char: '🫸', name: 'pushing right', keywords: ['push'] },
      { char: '🫷', name: 'pushing left', keywords: ['push'] },
      { char: '👌', name: 'OK hand', keywords: ['perfect'] },
      { char: '🤌', name: 'pinched fingers', keywords: ['italian'] },
      { char: '🤏', name: 'pinching hand', keywords: ['small'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace', 'two'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck'] },
      { char: '🫰', name: 'finger heart', keywords: ['korean heart'] },
      { char: '🤟', name: 'love you gesture', keywords: ['ily'] },
      { char: '🤘', name: 'horns', keywords: ['rock', 'metal'] },
      { char: '🤙', name: 'call me hand', keywords: ['shaka'] },
      { char: '👈', name: 'pointing left', keywords: ['left'] },
      { char: '👉', name: 'pointing right', keywords: ['right'] },
      { char: '👆', name: 'pointing up', keywords: ['up'] },
      { char: '👇', name: 'pointing down', keywords: ['down'] },
      { char: '☝️', name: 'index up', keywords: ['one'] },
      { char: '🫵', name: 'pointing at viewer', keywords: ['you'] },
      { char: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'good'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no'] },
      { char: '✊', name: 'raised fist', keywords: ['power'] },
      { char: '👊', name: 'fist bump', keywords: ['punch'] },
      { char: '🤛', name: 'left fist', keywords: ['fist bump'] },
      { char: '🤜', name: 'right fist', keywords: ['fist bump'] },
      { char: '👏', name: 'clapping hands', keywords: ['applause'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate'] },
      { char: '🫶', name: 'heart hands', keywords: ['love'] },
      { char: '👐', name: 'open hands', keywords: ['hug'] },
      { char: '🤲', name: 'palms together', keywords: ['prayer'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'partner'] },
      { char: '🙏', name: 'folded hands', keywords: ['please', 'thank you', 'namaste'] },
      { char: '✍️', name: 'writing hand', keywords: ['write', 'author'] },
      { char: '💅', name: 'nail polish', keywords: ['slay'] },
      { char: '🤳', name: 'selfie', keywords: ['camera'] },
      { char: '💪', name: 'biceps', keywords: ['strong', 'workout'] },
      { char: '🦾', name: 'bionic arm', keywords: ['cyborg', 'robot'] },
      { char: '🧠', name: 'brain', keywords: ['smart', 'mind'] },
      { char: '🫀', name: 'heart organ', keywords: ['cardiology'] },
      { char: '🫁', name: 'lungs', keywords: ['breath'] },
      { char: '👀', name: 'eyes', keywords: ['look', 'watching'] },
      { char: '👁️', name: 'eye', keywords: ['vision'] },
      { char: '👶', name: 'baby', keywords: ['child'] },
      { char: '🧒', name: 'child', keywords: ['kid'] },
      { char: '👦', name: 'boy', keywords: ['male'] },
      { char: '👧', name: 'girl', keywords: ['female'] },
      { char: '🧑', name: 'person', keywords: ['human'] },
      { char: '👨', name: 'man', keywords: ['guy'] },
      { char: '👩', name: 'woman', keywords: ['lady'] },
      { char: '🧓', name: 'older person', keywords: ['elder'] },
      { char: '👴', name: 'old man', keywords: ['grandfather'] },
      { char: '👵', name: 'old woman', keywords: ['grandmother'] },
      { char: '🧑‍⚕️', name: 'doctor', keywords: ['health', 'nurse'] },
      { char: '🧑‍🎓', name: 'student', keywords: ['graduate'] },
      { char: '🧑‍🏫', name: 'teacher', keywords: ['professor'] },
      { char: '🧑‍⚖️', name: 'judge', keywords: ['court', 'law'] },
      { char: '🧑‍💻', name: 'developer', keywords: ['coder', 'tech'] },
      { char: '🧑‍🎨', name: 'artist', keywords: ['painter'] },
      { char: '🧑‍🚀', name: 'astronaut', keywords: ['space'] },
      { char: '👮', name: 'police', keywords: ['cop'] },
      { char: '🕵️', name: 'detective', keywords: ['spy'] },
      { char: '💂', name: 'guard', keywords: ['sentinel'] },
      { char: '🥷', name: 'ninja', keywords: ['shinobi'] },
      { char: '🤴', name: 'prince', keywords: ['royalty'] },
      { char: '👸', name: 'princess', keywords: ['royalty'] },
      { char: '🦸', name: 'superhero', keywords: ['hero'] },
      { char: '🦹', name: 'supervillain', keywords: ['villain'] },
      { char: '🧙', name: 'wizard', keywords: ['magic'] },
      { char: '🧚', name: 'fairy', keywords: ['pixie'] },
      { char: '🧛', name: 'vampire', keywords: ['dracula'] },
      { char: '🚶', name: 'walking', keywords: ['walk'] },
      { char: '🏃', name: 'running', keywords: ['run', 'fast'] },
      { char: '💃', name: 'dancer', keywords: ['dance'] },
      { char: '🕺', name: 'disco dancer', keywords: ['dance'] },
      { char: '🧘', name: 'meditation', keywords: ['yoga', 'zen'] }
    ]
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: '🌿',
    emojis: [
      { char: '🐶', name: 'dog', keywords: ['puppy', 'pet'] },
      { char: '🐱', name: 'cat', keywords: ['kitten', 'pet'] },
      { char: '🐭', name: 'mouse', keywords: ['rodent'] },
      { char: '🐹', name: 'hamster', keywords: ['pet'] },
      { char: '🐰', name: 'rabbit', keywords: ['bunny'] },
      { char: '🦊', name: 'fox', keywords: ['clever', 'wild'] },
      { char: '🐻', name: 'bear', keywords: ['grizzly'] },
      { char: '🐼', name: 'panda', keywords: ['bamboo'] },
      { char: '🐻‍❄️', name: 'polar bear', keywords: ['arctic'] },
      { char: '🐨', name: 'koala', keywords: ['australia'] },
      { char: '🐯', name: 'tiger', keywords: ['feline'] },
      { char: '🦁', name: 'lion', keywords: ['king'] },
      { char: '🐮', name: 'cow', keywords: ['moo'] },
      { char: '🐷', name: 'pig', keywords: ['oink'] },
      { char: '🐸', name: 'frog', keywords: ['toad'] },
      { char: '🐵', name: 'monkey', keywords: ['chimp'] },
      { char: '🐔', name: 'chicken', keywords: ['rooster'] },
      { char: '🐧', name: 'penguin', keywords: ['arctic'] },
      { char: '🐦', name: 'bird', keywords: ['fly'] },
      { char: '🐤', name: 'chick', keywords: ['yellow'] },
      { char: '🦆', name: 'duck', keywords: ['quack'] },
      { char: '🦅', name: 'eagle', keywords: ['freedom'] },
      { char: '🦉', name: 'owl', keywords: ['wise'] },
      { char: '🦇', name: 'bat', keywords: ['night'] },
      { char: '🐺', name: 'wolf', keywords: ['pack'] },
      { char: '🐗', name: 'boar', keywords: ['wild'] },
      { char: '🐴', name: 'horse', keywords: ['pony'] },
      { char: '🦄', name: 'unicorn', keywords: ['magic'] },
      { char: '🐝', name: 'bee', keywords: ['honey'] },
      { char: '🐛', name: 'bug', keywords: ['insect'] },
      { char: '🦋', name: 'butterfly', keywords: ['beauty'] },
      { char: '🐌', name: 'snail', keywords: ['slow'] },
      { char: '🐞', name: 'ladybug', keywords: ['lucky'] },
      { char: '🐜', name: 'ant', keywords: ['work'] },
      { char: '🕷️', name: 'spider', keywords: ['web'] },
      { char: '🦂', name: 'scorpion', keywords: ['desert'] },
      { char: '🐢', name: 'turtle', keywords: ['slow'] },
      { char: '🐍', name: 'snake', keywords: ['hiss'] },
      { char: '🦖', name: 'T-Rex', keywords: ['dinosaur'] },
      { char: '🦕', name: 'sauropod', keywords: ['dinosaur'] },
      { char: '🐙', name: 'octopus', keywords: ['sea'] },
      { char: '🦑', name: 'squid', keywords: ['sea'] },
      { char: '🦐', name: 'shrimp', keywords: ['seafood'] },
      { char: '🦀', name: 'crab', keywords: ['beach'] },
      { char: '🐡', name: 'blowfish', keywords: ['fish'] },
      { char: '🐠', name: 'tropical fish', keywords: ['reef'] },
      { char: '🐟', name: 'fish', keywords: ['sea'] },
      { char: '🐬', name: 'dolphin', keywords: ['ocean'] },
      { char: '🐳', name: 'whale', keywords: ['huge'] },
      { char: '🦈', name: 'shark', keywords: ['ocean'] },
      { char: '🦭', name: 'seal', keywords: ['sea lion'] },
      { char: '🐊', name: 'crocodile', keywords: ['swamp'] },
      { char: '🐘', name: 'elephant', keywords: ['trunk'] },
      { char: '🐪', name: 'camel', keywords: ['desert'] },
      { char: '🦒', name: 'giraffe', keywords: ['tall'] },
      { char: '🦘', name: 'kangaroo', keywords: ['australia'] },
      { char: '🦌', name: 'deer', keywords: ['antlers'] },
      { char: '🦚', name: 'peacock', keywords: ['proud'] },
      { char: '🦜', name: 'parrot', keywords: ['talk'] },
      { char: '🦢', name: 'swan', keywords: ['lake'] },
      { char: '🦩', name: 'flamingo', keywords: ['pink'] },
      { char: '🕊️', name: 'dove', keywords: ['peace'] },
      { char: '🐇', name: 'rabbit', keywords: ['bunny'] },
      { char: '🐾', name: 'paw prints', keywords: ['pets'] },
      { char: '🐉', name: 'dragon', keywords: ['myth'] },
      { char: '🌵', name: 'cactus', keywords: ['desert'] },
      { char: '🌲', name: 'pine', keywords: ['forest'] },
      { char: '🌳', name: 'tree', keywords: ['nature'] },
      { char: '🌴', name: 'palm tree', keywords: ['beach'] },
      { char: '🌱', name: 'seedling', keywords: ['grow'] },
      { char: '🌿', name: 'herb', keywords: ['organic'] },
      { char: '☘️', name: 'shamrock', keywords: ['clover'] },
      { char: '🍀', name: 'four leaf clover', keywords: ['luck'] },
      { char: '🪴', name: 'potted plant', keywords: ['indoor'] },
      { char: '🍃', name: 'leaf in wind', keywords: ['breeze'] },
      { char: '🍂', name: 'fallen leaf', keywords: ['autumn'] },
      { char: '🍁', name: 'maple leaf', keywords: ['canada'] },
      { char: '🍄', name: 'mushroom', keywords: ['shroom'] },
      { char: '💐', name: 'bouquet', keywords: ['flowers'] },
      { char: '🌷', name: 'tulip', keywords: ['spring'] },
      { char: '🌹', name: 'rose', keywords: ['love', 'red'] },
      { char: '🌺', name: 'hibiscus', keywords: ['tropical'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['sakura'] },
      { char: '🌼', name: 'blossom', keywords: ['yellow'] },
      { char: '🌻', name: 'sunflower', keywords: ['sun'] },
      { char: '🌞', name: 'sun face', keywords: ['bright'] },
      { char: '🌕', name: 'full moon', keywords: ['night'] },
      { char: '🌙', name: 'crescent moon', keywords: ['sleep'] },
      { char: '🌎', name: 'globe Americas', keywords: ['earth', 'world'] },
      { char: '🌍', name: 'globe Europe-Africa', keywords: ['earth'] },
      { char: '🌏', name: 'globe Asia-Australia', keywords: ['earth'] },
      { char: '🪐', name: 'saturn', keywords: ['planet', 'space'] },
      { char: '⭐️', name: 'star', keywords: ['bright'] },
      { char: '🌟', name: 'glowing star', keywords: ['shine'] },
      { char: '✨', name: 'sparkles', keywords: ['magic'] },
      { char: '⚡️', name: 'lightning', keywords: ['power', 'zap'] },
      { char: '🔥', name: 'fire', keywords: ['flame', 'lit'] },
      { char: '🌈', name: 'rainbow', keywords: ['colors'] },
      { char: '☀️', name: 'sun', keywords: ['sunny'] },
      { char: '☁️', name: 'cloud', keywords: ['weather'] },
      { char: '🌧️', name: 'rain', keywords: ['shower'] },
      { char: '⛈️', name: 'thunderstorm', keywords: ['storm'] },
      { char: '❄️', name: 'snowflake', keywords: ['winter', 'cold'] },
      { char: '☃️', name: 'snowman', keywords: ['winter'] },
      { char: '🌊', name: 'wave', keywords: ['ocean', 'surf'] }
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { char: '🍏', name: 'green apple', keywords: ['fruit'] },
      { char: '🍎', name: 'red apple', keywords: ['fruit'] },
      { char: '🍐', name: 'pear', keywords: ['fruit'] },
      { char: '🍊', name: 'orange', keywords: ['citrus'] },
      { char: '🍋', name: 'lemon', keywords: ['sour'] },
      { char: '🍌', name: 'banana', keywords: ['fruit'] },
      { char: '🍉', name: 'watermelon', keywords: ['summer'] },
      { char: '🍇', name: 'grapes', keywords: ['wine'] },
      { char: '🍓', name: 'strawberry', keywords: ['berry'] },
      { char: '🫐', name: 'blueberries', keywords: ['berry'] },
      { char: '🍒', name: 'cherries', keywords: ['red'] },
      { char: '🍑', name: 'peach', keywords: ['fruit'] },
      { char: '🥭', name: 'mango', keywords: ['tropical'] },
      { char: '🍍', name: 'pineapple', keywords: ['tropical'] },
      { char: '🥥', name: 'coconut', keywords: ['palm'] },
      { char: '🥝', name: 'kiwi', keywords: ['fruit'] },
      { char: '🍅', name: 'tomato', keywords: ['salad'] },
      { char: '🥑', name: 'avocado', keywords: ['toast'] },
      { char: '🥦', name: 'broccoli', keywords: ['green'] },
      { char: '🥒', name: 'cucumber', keywords: ['pickle'] },
      { char: '🌶️', name: 'chili', keywords: ['spicy'] },
      { char: '🌽', name: 'corn', keywords: ['popcorn'] },
      { char: '🥕', name: 'carrot', keywords: ['rabbit'] },
      { char: '🧄', name: 'garlic', keywords: ['cooking'] },
      { char: '🥔', name: 'potato', keywords: ['fries'] },
      { char: '🥐', name: 'croissant', keywords: ['bakery'] },
      { char: '🍞', name: 'bread', keywords: ['toast'] },
      { char: '🥖', name: 'baguette', keywords: ['french'] },
      { char: '🥨', name: 'pretzel', keywords: ['snack'] },
      { char: '🧀', name: 'cheese', keywords: ['dairy'] },
      { char: '🍳', name: 'fried egg', keywords: ['breakfast'] },
      { char: '🥞', name: 'pancakes', keywords: ['breakfast'] },
      { char: '🧇', name: 'waffle', keywords: ['breakfast'] },
      { char: '🥓', name: 'bacon', keywords: ['breakfast'] },
      { char: '🥩', name: 'steak', keywords: ['meat'] },
      { char: '🍗', name: 'chicken leg', keywords: ['meat'] },
      { char: '🌭', name: 'hot dog', keywords: ['sausage'] },
      { char: '🍔', name: 'burger', keywords: ['fast food'] },
      { char: '🍟', name: 'fries', keywords: ['potato'] },
      { char: '🍕', name: 'pizza', keywords: ['italian'] },
      { char: '🫓', name: 'flatbread', keywords: ['roti', 'naan'] },
      { char: '🥪', name: 'sandwich', keywords: ['lunch'] },
      { char: '🌮', name: 'taco', keywords: ['mexican'] },
      { char: '🌯', name: 'burrito', keywords: ['mexican'] },
      { char: '🥗', name: 'salad', keywords: ['healthy'] },
      { char: '🍝', name: 'pasta', keywords: ['spaghetti'] },
      { char: '🍜', name: 'ramen', keywords: ['noodles'] },
      { char: '🍲', name: 'stew', keywords: ['soup'] },
      { char: '🍛', name: 'curry', keywords: ['indian'] },
      { char: '🍣', name: 'sushi', keywords: ['japanese'] },
      { char: '🍱', name: 'bento', keywords: ['lunch'] },
      { char: '🥟', name: 'dumpling', keywords: ['momo', 'dim sum'] },
      { char: '🍤', name: 'fried shrimp', keywords: ['tempura'] },
      { char: '🍙', name: 'rice ball', keywords: ['onigiri'] },
      { char: '🍚', name: 'rice', keywords: ['bowl'] },
      { char: '🍧', name: 'shaved ice', keywords: ['dessert'] },
      { char: '🍨', name: 'ice cream', keywords: ['dessert'] },
      { char: '🍦', name: 'soft serve', keywords: ['vanilla'] },
      { char: '🍰', name: 'cake', keywords: ['sweet'] },
      { char: '🎂', name: 'birthday cake', keywords: ['party'] },
      { char: '🍮', name: 'custard', keywords: ['pudding'] },
      { char: '🍭', name: 'lollipop', keywords: ['candy'] },
      { char: '🍬', name: 'candy', keywords: ['sweet'] },
      { char: '🍫', name: 'chocolate', keywords: ['cocoa'] },
      { char: '🍿', name: 'popcorn', keywords: ['cinema'] },
      { char: '🍩', name: 'doughnut', keywords: ['donut'] },
      { char: '🍪', name: 'cookie', keywords: ['biscuit'] },
      { char: '🍯', name: 'honey', keywords: ['sweet'] },
      { char: '🥛', name: 'milk', keywords: ['dairy'] },
      { char: '☕️', name: 'coffee', keywords: ['cafe', 'tea'] },
      { char: '🍵', name: 'tea', keywords: ['matcha'] },
      { char: '🧃', name: 'juice', keywords: ['drink'] },
      { char: '🥤', name: 'soda', keywords: ['cup'] },
      { char: '🧋', name: 'boba', keywords: ['bubble tea'] },
      { char: '🍺', name: 'beer', keywords: ['cheers'] },
      { char: '🍻', name: 'cheers', keywords: ['beers'] },
      { char: '🥂', name: 'champagne glasses', keywords: ['toast'] },
      { char: '🍷', name: 'wine', keywords: ['red wine'] },
      { char: '🥃', name: 'whiskey', keywords: ['scotch'] },
      { char: '🍸', name: 'cocktail', keywords: ['martini'] },
      { char: '🍹', name: 'tropical drink', keywords: ['vacation'] },
      { char: '🍾', name: 'champagne bottle', keywords: ['party'] },
      { char: '🍽️', name: 'plate', keywords: ['dining'] },
      { char: '🥢', name: 'chopsticks', keywords: ['asian'] }
    ]
  },
  {
    id: 'activities',
    name: 'Activities & Sports',
    icon: '🏆',
    emojis: [
      { char: '⚽️', name: 'soccer', keywords: ['football', 'fifa'] },
      { char: '🏀', name: 'basketball', keywords: ['nba'] },
      { char: '🏈', name: 'american football', keywords: ['nfl'] },
      { char: '⚾️', name: 'baseball', keywords: ['mlb'] },
      { char: '🎾', name: 'tennis', keywords: ['court'] },
      { char: '🏐', name: 'volleyball', keywords: ['beach'] },
      { char: '🏓', name: 'ping pong', keywords: ['table tennis'] },
      { char: '🏸', name: 'badminton', keywords: ['shuttlecock'] },
      { char: '🏒', name: 'ice hockey', keywords: ['nhl'] },
      { char: '🏏', name: 'cricket', keywords: ['ipl', 'bat'] },
      { char: '⛳️', name: 'golf', keywords: ['hole'] },
      { char: '🏹', name: 'archery', keywords: ['arrow'] },
      { char: '🥊', name: 'boxing', keywords: ['punch'] },
      { char: '🛹', name: 'skateboard', keywords: ['skate'] },
      { char: '🛼', name: 'roller skate', keywords: ['derby'] },
      { char: '⛷️', name: 'skiing', keywords: ['snow'] },
      { char: '🏋️', name: 'weightlifting', keywords: ['gym', 'fitness'] },
      { char: '🏆', name: 'trophy', keywords: ['winner', 'champion'] },
      { char: '🥇', name: 'gold medal', keywords: ['1st place'] },
      { char: '🥈', name: 'silver medal', keywords: ['2nd place'] },
      { char: '🥉', name: 'bronze medal', keywords: ['3rd place'] },
      { char: '🎫', name: 'ticket', keywords: ['pass', 'entry', 'event'] },
      { char: '🎟️', name: 'admission ticket', keywords: ['movie'] },
      { char: '🎪', name: 'circus', keywords: ['carnival'] },
      { char: '🎭', name: 'theater masks', keywords: ['drama'] },
      { char: '🎨', name: 'palette', keywords: ['art'] },
      { char: '🎬', name: 'clapper', keywords: ['movie', 'film'] },
      { char: '🎤', name: 'microphone', keywords: ['sing', 'karaoke'] },
      { char: '🎧', name: 'headphones', keywords: ['music', 'audio'] },
      { char: '🎼', name: 'musical score', keywords: ['notes'] },
      { char: '🎹', name: 'piano', keywords: ['music'] },
      { char: '🥁', name: 'drum', keywords: ['beat'] },
      { char: '🎷', name: 'saxophone', keywords: ['jazz'] },
      { char: '🎺', name: 'trumpet', keywords: ['brass'] },
      { char: '🎸', name: 'guitar', keywords: ['rock'] },
      { char: '🎻', name: 'violin', keywords: ['orchestra'] },
      { char: '🎲', name: 'dice', keywords: ['game'] },
      { char: '♟️', name: 'chess pawn', keywords: ['strategy'] },
      { char: '🎯', name: 'bullseye', keywords: ['target'] },
      { char: '🎮', name: 'gaming', keywords: ['controller', 'play'] },
      { char: '🎰', name: 'slot machine', keywords: ['casino'] },
      { char: '🧩', name: 'puzzle', keywords: ['jigsaw'] }
    ]
  },
  {
    id: 'objects',
    name: 'Objects & Tools',
    icon: '💡',
    emojis: [
      { char: '⌚️', name: 'watch', keywords: ['time'] },
      { char: '📱', name: 'phone', keywords: ['mobile', 'call'] },
      { char: '💻', name: 'laptop', keywords: ['computer', 'pc'] },
      { char: '⌨️', name: 'keyboard', keywords: ['type', 'code'] },
      { char: '🖥️', name: 'desktop', keywords: ['monitor'] },
      { char: '📷', name: 'camera', keywords: ['photo'] },
      { char: '📸', name: 'camera flash', keywords: ['photography'] },
      { char: '🎥', name: 'video camera', keywords: ['cinema'] },
      { char: '🎙️', name: 'studio mic', keywords: ['podcast'] },
      { char: '⏱️', name: 'stopwatch', keywords: ['timer'] },
      { char: '⏰', name: 'alarm clock', keywords: ['morning'] },
      { char: '💡', name: 'light bulb', keywords: ['idea', 'bright'] },
      { char: '🔦', name: 'flashlight', keywords: ['torch'] },
      { char: '💸', name: 'flying cash', keywords: ['money'] },
      { char: '💵', name: 'dollar', keywords: ['cash'] },
      { char: '🪙', name: 'coin', keywords: ['crypto', 'gold'] },
      { char: '💰', name: 'money bag', keywords: ['wealth'] },
      { char: '💳', name: 'credit card', keywords: ['visa', 'payment'] },
      { char: '💎', name: 'diamond', keywords: ['gem', 'precious'] },
      { char: '⚖️', name: 'scales', keywords: ['justice', 'law'] },
      { char: '🔧', name: 'wrench', keywords: ['fix', 'repair'] },
      { char: '🔨', name: 'hammer', keywords: ['build'] },
      { char: '🛠️', name: 'tools', keywords: ['developer'] },
      { char: '⚙️', name: 'gear', keywords: ['settings', 'cog'] },
      { char: '⛓️', name: 'chains', keywords: ['blockchain'] },
      { char: '💣', name: 'bomb', keywords: ['boom'] },
      { char: '⚔️', name: 'swords', keywords: ['battle'] },
      { char: '🛡️', name: 'shield', keywords: ['security', 'protect'] },
      { char: '🔮', name: 'crystal ball', keywords: ['future'] },
      { char: '🧪', name: 'test tube', keywords: ['chemistry', 'lab'] },
      { char: '🧬', name: 'dna', keywords: ['science'] },
      { char: '🔬', name: 'microscope', keywords: ['research'] },
      { char: '🔑', name: 'key', keywords: ['password', 'access'] },
      { char: '🗝️', name: 'vintage key', keywords: ['secret'] },
      { char: '🔒', name: 'locked', keywords: ['security'] },
      { char: '🔓', name: 'unlocked', keywords: ['open'] },
      { char: '📦', name: 'package', keywords: ['box'] },
      { char: '✉️', name: 'envelope', keywords: ['email', 'mail'] },
      { char: '📜', name: 'scroll', keywords: ['document', 'treaty'] },
      { char: '📄', name: 'page', keywords: ['file', 'paper'] },
      { char: '📊', name: 'bar chart', keywords: ['stats'] },
      { char: '📈', name: 'chart up', keywords: ['growth'] },
      { char: '📉', name: 'chart down', keywords: ['loss'] },
      { char: '📅', name: 'calendar', keywords: ['date', 'event'] },
      { char: '📁', name: 'folder', keywords: ['directory'] },
      { char: '🗞️', name: 'newspaper', keywords: ['press'] },
      { char: '📖', name: 'book', keywords: ['read'] },
      { char: '🔖', name: 'bookmark', keywords: ['save'] },
      { char: '🔗', name: 'link', keywords: ['url'] },
      { char: '📌', name: 'pushpin', keywords: ['pinned'] },
      { char: '📍', name: 'location pin', keywords: ['map'] },
      { char: '✂️', name: 'scissors', keywords: ['cut'] },
      { char: '🖊️', name: 'pen', keywords: ['write'] },
      { char: '🖋️', name: 'fountain pen', keywords: ['diplomat'] },
      { char: '📝', name: 'memo', keywords: ['notes', 'draft'] },
      { char: '🔍', name: 'search', keywords: ['find'] }
    ]
  },
  {
    id: 'symbols_flags',
    name: 'Symbols & Flags',
    icon: '🚩',
    emojis: [
      { char: '☮️', name: 'peace', keywords: ['harmony'] },
      { char: '☯️', name: 'yin yang', keywords: ['balance', 'zen'] },
      { char: '⚛️', name: 'atom', keywords: ['science'] },
      { char: '⚠️', name: 'warning', keywords: ['alert', 'caution'] },
      { char: '⛔️', name: 'no entry', keywords: ['forbidden'] },
      { char: '🚫', name: 'prohibited', keywords: ['ban'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'cancel'] },
      { char: '🛑', name: 'stop sign', keywords: ['halt'] },
      { char: '💯', name: '100 points', keywords: ['perfect'] },
      { char: '❗️', name: 'exclamation', keywords: ['red'] },
      { char: '❓', name: 'question mark', keywords: ['query'] },
      { char: '‼️', name: 'double exclamation', keywords: ['urgent'] },
      { char: '♻️', name: 'recycle', keywords: ['green', 'eco'] },
      { char: '✅', name: 'check mark', keywords: ['done', 'yes', 'verified'] },
      { char: '🌐', name: 'globe web', keywords: ['internet'] },
      { char: '💠', name: 'diamond dot', keywords: ['crystal'] },
      { char: 'ℹ️', name: 'info', keywords: ['help'] },
      { char: '🆗', name: 'OK', keywords: ['agree'] },
      { char: '🆙', name: 'UP', keywords: ['level up'] },
      { char: '🆒', name: 'COOL', keywords: ['rad'] },
      { char: '🆕', name: 'NEW', keywords: ['fresh'] },
      { char: '🆓', name: 'FREE', keywords: ['zero cost'] },
      { char: '▶️', name: 'play', keywords: ['start'] },
      { char: '⏸️', name: 'pause', keywords: ['freeze'] },
      { char: '⏹️', name: 'stop', keywords: ['halt'] },
      { char: '🎵', name: 'music note', keywords: ['melody'] },
      { char: '🎶', name: 'musical notes', keywords: ['soundtrack'] },
      { char: '♾️', name: 'infinity', keywords: ['endless'] },
      { char: '💲', name: 'dollar sign', keywords: ['money'] },
      { char: '™️', name: 'trademark', keywords: ['legal'] },
      { char: '©️', name: 'copyright', keywords: ['rights'] },
      { char: '🏁', name: 'chequered flag', keywords: ['race'] },
      { char: '🚩', name: 'red flag', keywords: ['post'] },
      { char: '🏴', name: 'black flag', keywords: ['sovereign'] },
      { char: '🏳️', name: 'white flag', keywords: ['peace'] },
      { char: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride'] },
      { char: '🏴‍☠️', name: 'pirate flag', keywords: ['jolly roger'] },
      { char: '🇮🇳', name: 'India', keywords: ['bharat', 'tricolor'] },
      { char: '🇺🇸', name: 'USA', keywords: ['america'] },
      { char: '🇬🇧', name: 'UK', keywords: ['britain'] },
      { char: '🇯🇵', name: 'Japan', keywords: ['nippon'] },
      { char: '🇩🇪', name: 'Germany', keywords: ['deutschland'] },
      { char: '🇫🇷', name: 'France', keywords: ['french'] },
      { char: '🇨🇦', name: 'Canada', keywords: ['maple'] },
      { char: '🇦🇺', name: 'Australia', keywords: ['aussie'] },
      { char: '🇮🇹', name: 'Italy', keywords: ['italia'] },
      { char: '🇪🇸', name: 'Spain', keywords: ['espana'] },
      { char: '🇧🇷', name: 'Brazil', keywords: ['brasil'] },
      { char: '🇷🇺', name: 'Russia', keywords: ['rossiya'] },
      { char: '🇨🇳', name: 'China', keywords: ['prc'] },
      { char: '🇰🇷', name: 'South Korea', keywords: ['korea'] },
      { char: '🇲🇽', name: 'Mexico', keywords: ['mexico'] },
      { char: '🇸🇦', name: 'Saudi Arabia', keywords: ['ksa'] },
      { char: '🇹🇷', name: 'Turkey', keywords: ['turkiye'] },
      { char: '🇿🇦', name: 'South Africa', keywords: ['rsa'] },
      { char: '🇦🇪', name: 'UAE', keywords: ['dubai'] },
      { char: '🇨🇭', name: 'Switzerland', keywords: ['swiss'] },
      { char: '🇸🇬', name: 'Singapore', keywords: ['singapore'] },
      { char: '🇳🇱', name: 'Netherlands', keywords: ['holland'] },
      { char: '🇸🇪', name: 'Sweden', keywords: ['sverige'] },
      { char: '🇳🇴', name: 'Norway', keywords: ['norge'] }
    ]
  }
];

export const ALL_EMOJIS: EmojiItem[] = UNIVERSAL_EMOJI_CATEGORIES.flatMap(c => c.emojis);

